import React from "react";
import { FiTrash2 } from "react-icons/fi";
import {
  BiDollarCircle,
  BiEditAlt,
  BiHomeAlt2,
  BiInfoCircle,
  BiLogOutCircle,
  BiSearch,
  BiTrash,
} from "react-icons/bi";
import { IoIosArrowRoundBack, IoMdClose } from "react-icons/io";
import {
  BsCheckLg,
  BsChevronDown,
  BsChevronLeft,
  BsChevronRight,
  BsFillBoxFill,
  BsFillCheckCircleFill,
  BsPlusLg,
  BsReply,
  BsThreeDotsVertical,
  BsWallet2,
} from "react-icons/bs";
import { HiOutlineChevronDown, HiChevronUp, HiMenu } from "react-icons/hi";
import {
  AiFillCamera,
  AiFillEye,
  AiFillEyeInvisible,
  AiFillHeart,
  AiFillLike,
  AiFillStar,
  AiOutlineHeart,
  AiOutlineLike,
  AiOutlineMinus,
  AiOutlineStar,
  AiOutlineUnorderedList,
} from "react-icons/ai";
export const reactIcons = {
  plus: <BsPlusLg />,
  minus: <AiOutlineMinus />,
  trash: <BiTrash />,
  edit: <BiEditAlt />,
  eyeslash: <AiFillEyeInvisible />,
  eye: <AiFillEye />,
  arrowDown: <HiOutlineChevronDown />,
  arrowUp: <HiChevronUp />,
  unlike: <AiOutlineLike />,
  like: <AiFillLike />,
  check: <BsCheckLg />,
  camera: <AiFillCamera />,
  reply: <BsReply />,
  close: <IoMdClose />,
  heartFill: <AiFillHeart />,
  starFill: <AiFillStar />,
  starOutline: <AiOutlineStar />,
  heartOutline: <AiOutlineHeart />,
  home: <BiHomeAlt2 />,
  logout: <BiLogOutCircle />,
  list: <AiOutlineUnorderedList />,
  arrowleft: <BsChevronLeft />,
  arrowright: <BsChevronRight />,
  arrowdown: <BsChevronDown />,
  success: <BsFillCheckCircleFill />,
  info: <BiInfoCircle />,
  delete: <FiTrash2 />,
  search: <BiSearch />,
  menu: <HiMenu />,
  threeDots: <BsThreeDotsVertical />,
  eyes: <AiFillEye />,
  goback: <IoIosArrowRoundBack />,
  star: <AiOutlineStar />,
  profit: <BiDollarCircle />,
  vault: <BsWallet2 />,
  product: <BsFillBoxFill />,
};
